config/routes.rb
Music::Application.routes.draw do

  resources :artists
  resources :bands do
    member do
      get "photo"
    end
  end
  resources :songs

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	[	:first_name,
		:last_name,
		:alias,
		:band_id	].each { |field| attr_accessible field }

	[	:first_name,
		:last_name ].each { |field| validates field, :presence => true }

	[ :first_name,
		:last_name ].each { |field| validates field, :length => (3..15) }

	before_validation :nil_if_blank

	belongs_to :band
	has_many :authored_songs, :foreign_key => :author_id, :class_name => "Song"
	has_many :recordings, :through => :band
	has_many :performed_songs, :through => :recordings, :source => :song

	# returns a hash containing, for each artist, an array of his songs
	def self.recorded_songs
		artists = self.includes(:authored_songs)
		authored_songs = {}
		artists.each do |artist|
			authored_songs[artist] = artist.authored_songs
		end
		authored_songs
	end

	def nil_if_blank
		self.alias = nil if self.alias.blank?
		true
	end

end

app/models/band.rb
class Band < ActiveRecord::Base

	attr_accessible :name, :photo
	validates :name, :presence => true, :uniqueness => true

	has_many :artists
	has_many :recordings
	has_many :songs, :through => :recordings

	# finds bands who have recorded the same song > 1 time
	def self.repeat_recorders
		self
			.select("bands.*, COUNT(DISTINCT(recordings.song_id)) AS song_count, songs.name AS song_name")
			.joins(:songs)
			.group("bands.id")
			.having("COUNT(DISTINCT(recordings.song_id)) < COUNT(recordings.song_id)")
	end

	def num_distinct_recordings
		self.songs.uniq.count
	end

end

app/models/recording.rb
class Recording < ActiveRecord::Base

	attr_accessible :song_id, :band_id
  validates :song_id, :presence => true
  validates :band_id, :presence => true

	belongs_to :band
	belongs_to :song

end

app/models/song.rb
class Song < ActiveRecord::Base

	attr_accessible :name, :author_id
  validates :name, :presence => true
  validates :author_id, :presence => true

	belongs_to :artist, :foreign_key => :author_id
	has_many :recordings
	has_many :bands, :through => :recordings
	has_many :performing_artists, :through => :bands, :source => :artists


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    # get all artists to display
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @artist_name = "#{@artist.first_name} #{@artist.last_name}"
    @artist.band.nil? ? @artist_band = "No One" : @artist_band = @artist.band
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(params[:artist])
    if @artist.save
      redirect_to @artist, :notice => "Congratulations on your new Artist page!"
    else
      flash[:error] = @artist.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update_attributes(params[:artist])

    if @artist.save
      redirect_to @artist, :notice => "You've successfully updated your artist information"
    else
      flash[:error] = @artist.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    del_name = @artist.first_name
    if @artist.destroy
      redirect_to artists_path, :notice => "#{del_name} was successfully deleted"
    else
      flash[:error] = @artist.errors.full_messages.to_sentence
      redirect_to artists_path
    end
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
     photo_blob = params[:band].delete(:photo).read
     @band = Band.new(params[:band])
     @band.photo = photo_blob

    if @band.save
      redirect_to @band, :notice => "Congratulations on forming your band!"
    else
      flash[:error] = @band.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    photo_blob = params[:band].delete(:photo).read
    @band = Band.find(params[:id])
    @band.update_attributes(params[:band])
    @band.photo = photo_blob

    if @band.save
      redirect_to @band, :notice => "You've successfully updated your band info"
    else
      flash[:error] = @band.errors.full_messages.to_sentence
      render :edit
    end
  end

  def photo
    @band = Band.find(params[:id])
    send_data @band.photo, :type => 'image/jpg'
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new

  end

  def create

  end

  def show
    @song = Song.find(params[:id])
  end

  def edit

  end

  def index
    @songs = Song.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_action_links.html.erb
<ul>
  <li>
    <%= link_to "Edit #{@artist.first_name}'s Information", edit_artist_path %>
  </li>
</ul>
<hr />

app/views/artists/_artist.html.erb
<li>
  <%= link_to "#{artist.first_name} #{artist.last_name}", artist %>
</li>

app/views/artists/_form.html.erb
<% if @artist.id.nil? %>
  <% verb = "Create" %>
<% else %>
  <% verb = "Edit" %>
<% end %>

<h3>
  <%= "#{verb} an Artist:" %>
</h3>

<%= form_for @artist do |f|%>
  <br />
  <%= f.label :first_name, "First Name: " %>
  <%= f.text_field :first_name %>
  <br />
  <%= f.label :last_name, "Last Name: " %>
  <%= f.text_field :last_name %>
  <br />
  <%= f.label :alias, "Alias (optional): " %>
  <%= f.text_field :alias %>
  <br />
  <%= f.submit "#{verb} Artist" %>
<% end %>

app/views/artists/_songs_written.html.erb
<hr />
<h3>Songs Written:</h3>
<ul>
  <% @artist.authored_songs.each do |song| %>
    <li>
      <%= link_to song.name, song %>
    </li>
  <% end %>
</ul>

app/views/artists/_tracks_recorded.html.erb
<hr />
<h3>Tracks Recorded:</h3>
<ul>
  <% @artist.recordings.each do |recording| %>
    <li>
      <%= link_to recording.song.name, recording.song %>
      with
      <%= link_to recording.band.name, recording.band %>
    </li>
  <% end %>
</ul>

app/views/artists/edit.html.erb
<%= render "form" %>

app/views/artists/index.html.erb
<h1>Welcome to the Artists page!</h1>

<h4>Create a new Artist page <%= link_to "HERE", new_artist_path %></h4>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <% artist.alias.nil? ? aka = "" : aka = ", aka '#{artist.alias}'" %>
      <%= link_to "#{artist.first_name} #{artist.last_name}#{aka}", artist %>
      <%= button_to("delete artist?", artist, :method => :delete, :confirm => "Really???") %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<%= render "form" %>

app/views/artists/show.html.erb
<h1>
  <%="Welcome to #{@artist_name}'s Artist Page"%>
</h1>
<hr />


<%= render "action_links" %>

<h3>Vital Stats:</h3>
<h4>
  <% if @artist.band.nil? %>
    <%= ">> Currently not with a band" %>
    <% else %>
      <%= ">> Currently recording with " %>
      <%= link_to @artist.band.name, @artist.band %>
  <% end %>
</h4>
<h4>
  <%= ">> Has written #{@artist.authored_songs.count} songs" %>
</h4>
<h4>
  <%= ">> Has recorded #{@artist.performed_songs.count} tracks" %>
</h4>

<%= render "songs_written" unless @artist.authored_songs.size == 0 %>
<%= render "tracks_recorded" unless @artist.performed_songs.size == 0 %>

app/views/bands/_action_links.html.erb
<ul>
  <li>
    <%= link_to "Edit #{@band.name}'s Information", edit_band_path %>
  </li>
</ul>
<hr />

app/views/bands/_tracks_recorded.html.erb
<hr />
<h3>Tracks Recorded:</h3>
<ul>
  <% @band.recordings.each do |recording| %>
    <li>
      <%= link_to recording.song.name, recording.song %>
    </li>
  <% end %>
</ul>

app/views/bands/edit.html.erb
<h3>Edit the Band:</h3>

<%= form_for @band do |f|%>
  <br />
  <%= f.label :name, "Band Name: " %>
  <%= f.text_field :name %>
  <br />
  <%= f.submit "Update Band Info!"  %>
<% end %>

app/views/bands/index.html.erb
<h2>Welcome to the Bands page!</h2>

<h4>Create a new Band page <%= link_to "HERE", new_band_path %></h4>

<ul>
  <% @bands.each do |band| %>
    <li>
      <%= link_to "#{band.name}", band %>
      <%= button_to("delete band?", band, :method => :delete, :confirm => "Really???") %>
    </li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h3>Create a new Band:</h3>

<%= form_for @band do |f|%>
  <br />
  <%= f.label :name, "Band Name: " %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :photo, "Upload your Band photo" %><br />
  <%= f.file_field(:photo) %>
  <br />
  <%= f.submit "Create Band"  %>

<% end %>

app/views/bands/show.html.erb
<h2>
  <%="Welcome to #{@band.name}'s Band Page"%>
</h2>
<hr />


<%= render "action_links" %>

<%= image_tag photo_band_path(@band), :alt => "Band Photo" %>

<h3>Vital Stats:</h3>
<h4>
  CURRENT PICTURES <br />
  <% if @band.artists.nil? %>
    <%=  ">> This band needs musicians!" %>
  <% else %>
      <%= ">> Current Members: " %>
      <%= render @band.artists %>
    <% end %>
</h4>
<h4>
  <%= ">> Recorded #{@band.num_distinct_recordings} distinct song(s)" %>
</h4>
<h4>
  <%= ">> Recorded #{@band.recordings.count} track(s)" %>
</h4>

<%= render "tracks_recorded" unless @band.recordings.count == 0 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= flash[:error] %>
<% if flash[:notice] or flash[:error]  %>
  <br />
<% end %>
<%= render "shared/nav_links" %>
<%= yield %>

</body>
</html>

app/views/shared/_nav_links.html.erb
<em>&nbsp;&nbsp;&nbsp;&nbsp; Jump to:
  <%= link_to "Artists", artists_path %> |
  <%= link_to "Bands", bands_path %> |
  <%= link_to "Songs", songs_path %>
</em>

app/views/songs/index.html.erb
<h1>Welcome to the Songs page!</h1>

<h4>Create a new Song page <%= link_to "HERE", new_song_path %></h4>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to "#{song.name}", song %>
      <%= button_to("delete song?", song, :method => :delete, :confirm => "Really???") %>
    </li>
  <% end %>
</ul>

app/views/songs/show.html.erb
<%= render "shared/nav_links" %>

<h2><%= @song.name %></h2>